- type: department
  id: CP14Free
  description: department-CP14Free-desc
  color: "#429976"
  roles:
  - CP14JobAdventurer
  - CP14JobAlchemist

- type: department
  id: CP14Command
  description: department-CP14Command-desc
  color: "#fadb3e"
