- type: job
  id: Adventurer
  name: job-name-adventurer
  description: job-description-adventurer
  playTimeTracker: JobAdventurer
  startingGear: CPTestGear
  icon: "JobIconCargoTechnician" #TODO replace
  supervisors: job-supervisors-everyone

- type: startingGear
  id: CPTestGear
  equipment:
    shirt: CPClothingShirtHarlequineRed
    pants: CPClothingPantsHarlequinRed
    shoes: CPClothingShoesBlack